version: '3.5'
services:
    database:
        image: shopee-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: shopee_test
            MYSQL_USER: shopee_user
            MYSQL_PASSWORD: shopee_pass
        volumes:
            - .db/docker-entrypoint-initdb.d
            - db-volume:/var/lib/mysql
volumes:
    db-volume: